version: '3.8'
services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/difficulties-pushup-gaps
    volumes:
      - ./data/neo4j/seeds:/import
    restart: always