version: '3.8'
services:
  neo4j:
    container_name: ${APP_NAME}-neo4j
    image: neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/neo4j/data:/data
      - $HOME/neo4j/neo4j/logs:/logs
      - $HOME/neo4j/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
    restart: always
  streamlit:
    container_name: groupint-streamlit
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=localhost
      - NEO4J_URI=bolt://${APP_NAME}-neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=difficulties-pushup-gaps
      - APP_NAME=${APP_NAME}
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - neo4j