#!/usr/bin/env python3
"""Merge modular docs/ into a single groupint-manual.md for PDF export."""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
OUTPUT_PATH = DOCS_DIR / "groupint-manual.md"

BANNER = (
    "<!-- AUTO-GENERATED by scripts/build-docs.sh — edit source files under docs/ -->\n\n"
)

# (path relative to docs/, chapter H1 title, optional appendix label)
CHAPTERS: list[tuple[str, str]] = [
    ("index.md", "Introduction"),
    ("overview.md", "Overview"),
    ("installation.md", "Installation"),
    ("configuration.md", "Configuration"),
    ("docker/desktop-stack.md", "Docker: Desktop Stack"),
    ("docker/full-stack-with-atlos.md", "Docker: Full Stack with Atlos"),
    ("telegram/credentials-and-api.md", "Telegram: Credentials and API Keys"),
    ("telegram/sessions-and-auth.md", "Telegram: Sessions and Authentication"),
    ("main-application.md", "Main Application"),
    ("neo4j-and-gephi.md", "Neo4j and Gephi"),
    ("incidents/overview.md", "Incidents: Overview"),
    ("incidents/watchlist-and-import.md", "Incidents: Watchlist and Bulk Import"),
    ("incidents/keywords-and-scheduler.md", "Incidents: Keywords and Scheduler"),
    ("incidents/atlos-export.md", "Incidents: Atlos Export"),
    ("troubleshooting.md", "Troubleshooting"),
    ("development.md", "Appendix: Development"),
    ("tutorial-full-workflow-uk.md", "Appendix: Tutorial (Ukrainian)"),
]

TOC_SECTION_START = "## Table of contents"
ARCHITECTURE_SECTION = "## Architecture (high level)"


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    return re.sub(r"-+", "-", text).strip("-")


def build_anchor_map() -> dict[str, str]:
    """Map normalized docs-relative paths to chapter anchors."""
    anchors: dict[str, str] = {}
    for relpath, title in CHAPTERS:
        anchor = slugify(title)
        anchors[relpath.replace("\\", "/")] = anchor
        # Also index by basename for same-dir links (e.g. overview.md from incidents/)
        name = Path(relpath).name
        if name not in anchors or "/" not in relpath:
            pass
        # Prefer full path; basename-only resolved at link time with context
    return {rp.replace("\\", "/"): slugify(t) for rp, t in CHAPTERS}


def normalize_doc_path(path: str) -> str:
    return path.replace("\\", "/")


def resolve_md_path(current_relpath: str, href: str) -> str | None:
    href = href.split("#")[0].strip()
    if not href.endswith(".md"):
        return None
    current = DOCS_DIR / current_relpath
    target = (current.parent / href).resolve()
    try:
        rel = target.relative_to(DOCS_DIR.resolve())
    except ValueError:
        return None
    return normalize_doc_path(str(rel))


def demote_headings(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.startswith("#"):
            hashes = len(line) - len(line.lstrip("#"))
            if hashes < 6:
                line = "#" + line
        lines.append(line)
    return "\n".join(lines)


def rewrite_md_links(text: str, current_relpath: str, anchor_map: dict[str, str]) -> str:
    def repl(match: re.Match[str]) -> str:
        label, href = match.group(1), match.group(2)
        if href.startswith(("http://", "https://", "mailto:")):
            return match.group(0)
        fragment = ""
        if "#" in href:
            href, fragment = href.split("#", 1)
            fragment = "#" + fragment
        resolved = resolve_md_path(current_relpath, href)
        if resolved is None:
            return match.group(0)
        anchor = anchor_map.get(resolved)
        if anchor is None:
            # Try basename match within incidents/ or telegram/
            base = Path(resolved).name
            for key, anc in anchor_map.items():
                if Path(key).name == base:
                    anchor = anc
                    break
        if anchor is None:
            return match.group(0)
        return f"[{label}](#{anchor}{fragment})"

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, text)


def process_index_body(content: str) -> str:
    """Keep intro and quick links; drop modular TOC; keep architecture and repo."""
    if TOC_SECTION_START not in content:
        return demote_headings(content)

    before_toc, rest = content.split(TOC_SECTION_START, 1)
    if ARCHITECTURE_SECTION in rest:
        _, after_toc = rest.split(ARCHITECTURE_SECTION, 1)
        chapter_list = "\n".join(
            f"- [{title}](#{slugify(title)})" for _, title in CHAPTERS[1:]
        )
        toc_replacement = (
            "## Chapters in this manual\n\n"
            "This file combines all guides from `docs/`. "
            "Edit the modular sources, then run `./scripts/build-docs.sh`.\n\n"
            f"{chapter_list}\n\n"
        )
        body = (
            before_toc.rstrip()
            + "\n\n"
            + toc_replacement
            + ARCHITECTURE_SECTION
            + after_toc
        )
    else:
        body = before_toc

    # Drop duplicate top-level title; chapter wrapper supplies H1
    body = re.sub(r"^# Groupint documentation\s*\n+", "", body, count=1)
    return demote_headings(body)


def load_chapter_body(relpath: str, anchor_map: dict[str, str]) -> str:
    path = DOCS_DIR / relpath
    if not path.is_file():
        raise FileNotFoundError(f"Missing doc source: {path}")
    content = path.read_text(encoding="utf-8")

    if relpath == "index.md":
        content = process_index_body(content)
    else:
        content = re.sub(r"^#\s+.+\s*\n+", "", content, count=1)
        content = demote_headings(content)

    return rewrite_md_links(content, relpath, anchor_map)


def merge() -> str:
    anchor_map = build_anchor_map()
    parts = [
        BANNER,
        "# Groupint User Manual\n\n",
        "Complete documentation for "
        "[Groupint](https://github.com/OSINT-for-Ukraine/groupint) "
        "by [OSINT for Ukraine](https://www.osintforukraine.com/).\n\n",
    ]

    for relpath, title in CHAPTERS:
        anchor = slugify(title)
        body = load_chapter_body(relpath, anchor_map)
        parts.append(f"\n\n---\n\n# {title} {{#{anchor}}}\n\n")
        parts.append(body.strip())
        parts.append("\n")

    return "".join(parts).rstrip() + "\n"


def main() -> int:
    missing = [rp for rp, _ in CHAPTERS if not (DOCS_DIR / rp).is_file()]
    if missing:
        print("Missing documentation sources:", file=sys.stderr)
        for rp in missing:
            print(f"  - docs/{rp}", file=sys.stderr)
        return 1

    OUTPUT_PATH.write_text(merge(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
